[package]
name = "ratatui"
version = "0.20.1"
authors = ["Florian Dehau <work@fdehau.com>"]
description = """
A library to build rich terminal user interfaces or dashboards
"""
documentation = "https://docs.rs/ratatui/latest/ratatui/"
keywords = ["tui", "terminal", "dashboard"]
repository = "https://github.com/tui-rs-revival/ratatui"
readme = "README.md"
license = "MIT"
exclude = ["assets/*", ".github", "Makefile.toml", "CONTRIBUTING.md", "*.log", "tags"]
autoexamples = true
edition = "2021"
rust-version = "1.59.0"

[badges]

[features]
default = ["crossterm"]
all-widgets = ["widget-calendar"]
widget-calendar = ["time"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
bitflags = "1.3"
cassowary = "0.3"
unicode-segmentation = "1.10"
unicode-width = "0.1"
termion = { version = "2.0", optional = true }
crossterm = { version = "0.26", optional = true }
serde = { version = "1", optional = true, features = ["derive"]}
time = { version = "0.3.11", optional = true, features = ["local-offset"]}

[dev-dependencies]
rand = "0.8"
argh = "0.1"
indoc = "2.0"

[[example]]
name = "barchart"
required-features = ["crossterm"]

[[example]]
name = "block"
required-features = ["crossterm"]

[[example]]
name = "canvas"
required-features = ["crossterm"]

[[example]]
name = "calendar"
required-features = ["crossterm", "widget-calendar"]

[[example]]
name = "chart"
required-features = ["crossterm"]

[[example]]
name = "custom_widget"
required-features = ["crossterm"]

[[example]]
name = "gauge"
required-features = ["crossterm"]

[[example]]
name = "layout"
required-features = ["crossterm"]

[[example]]
name = "list"
required-features = ["crossterm"]

[[example]]
name = "panic"
required-features = ["crossterm"]

[[example]]
name = "paragraph"
required-features = ["crossterm"]

[[example]]
name = "popup"
required-features = ["crossterm"]

[[example]]
name = "sparkline"
required-features = ["crossterm"]

[[example]]
name = "table"
required-features = ["crossterm"]

[[example]]
name = "tabs"
required-features = ["crossterm"]

[[example]]
name = "user_input"
required-features = ["crossterm"]

[[example]]
name = "inline"
required-features = ["crossterm"]
