[package]
name = "ratatui"
version = "0.23.0" # crate version
authors = ["Florian Dehau <work@fdehau.com>", "The Ratatui Developers"]
description = "A library that's all about cooking up terminal user interfaces"
documentation = "https://docs.rs/ratatui/latest/ratatui/"
keywords = ["tui", "terminal", "dashboard"]
repository = "https://github.com/ratatui-org/ratatui"
readme = "README.md"
license = "MIT"
exclude = [
  "assets/*",
  ".github",
  "Makefile.toml",
  "CONTRIBUTING.md",
  "*.log",
  "tags",
]
autoexamples = true
edition = "2021"
rust-version = "1.67.0"

[badges]

[dependencies]
#! The crate provides a set of optional features that can be enabled in your `cargo.toml` file.
#!
#! Generally an application will only use one backend, so you should only enable one of the following features:
## enables the [`CrosstermBackend`] backend and adds a dependency on the [Crossterm crate].
crossterm = { version = "0.27", optional = true }
## enables the [`TermionBackend`] backend and adds a dependency on the [Termion crate].
termion = { version = "2.0", optional = true }
## enables the [`TermwizBackend`] backend and adds a dependency on the [Termwiz crate].
termwiz = { version = "0.20.0", optional = true }

serde = { version = "1", optional = true, features = ["derive"] }
bitflags = "2.3"
cassowary = "0.3"
indoc = "2.0"
itertools = "0.11"
paste = "1.0.2"
strum = { version = "0.25", features = ["derive"] }
time = { version = "0.3.11", optional = true, features = ["local-offset"] }
unicode-segmentation = "1.10"
unicode-width = "0.1"
document-features = { version = "0.2.7", optional = true }

[dev-dependencies]
anyhow = "1.0.71"
argh = "0.1"
cargo-husky = { version = "1.5.0", default-features = false, features = [
  "user-hooks",
] }
criterion = { version = "0.5", features = ["html_reports"] }
fakeit = "1.1"
rand = "0.8"
pretty_assertions = "1.4.0"

[features]
default = ["crossterm"]
#! The following optional features are available for all backends:
## enables serialization and deserialization of style and color types using the [Serde crate].
## This is useful if you want to save themes to a file.
serde = ["dep:serde", "bitflags/serde"]

## enables the [`border!`] macro.
macros = []

## enables all widgets.
all-widgets = ["widget-calendar"]

#! Widgets that add dependencies are gated behind feature flags to prevent unused transitive
#! dependencies. The available features are:
## enables the [`calendar`] widget module and adds a dependency on the [Time crate].
widget-calendar = ["dep:time"]

[package.metadata.docs.rs]
all-features = true
# see https://doc.rust-lang.org/nightly/rustdoc/scraped-examples.html
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "barchart"
harness = false

[[bench]]
name = "block"
harness = false

[[bench]]
name = "list"
harness = false

[[bench]]
name = "paragraph"
harness = false

[[bench]]
name = "sparkline"
harness = false


[[example]]
name = "barchart"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "block"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "canvas"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "calendar"
required-features = ["crossterm", "widget-calendar"]
doc-scrape-examples = true

[[example]]
name = "chart"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "colors"
required-features = ["crossterm"]
# this example is a bit verbose, so we don't want to include it in the docs
doc-scrape-examples = false

[[example]]
name = "custom_widget"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "demo"
# this runs for all of the terminal backends, so it can't be built using --all-features or scraped
doc-scrape-examples = false

[[example]]
name = "gauge"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "hello_world"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "layout"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "list"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "modifiers"
required-features = ["crossterm"]
# this example is a bit verbose, so we don't want to include it in the docs
doc-scrape-examples = false

[[example]]
name = "panic"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "paragraph"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "popup"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "scrollbar"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "sparkline"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "table"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "tabs"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "user_input"
required-features = ["crossterm"]
doc-scrape-examples = true

[[example]]
name = "inline"
required-features = ["crossterm"]
doc-scrape-examples = true
