name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-stable:
    name: Create a stable release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Publish on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_TOKEN }}
